-- MySQL Script generated by MySQL Workbench
-- Sun Apr 12 14:38:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tutorin
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema orm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema orm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `orm` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `orm` ;

-- -----------------------------------------------------
-- Table `orm`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`categories` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `orm`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `birthday` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `numbre_phone` VARCHAR(45) NULL,
  `active` VARCHAR(45) NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `orm`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`comments` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `body` TEXT NOT NULL,
  `commentable_type` VARCHAR(255) NOT NULL,
  `commentable_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `comments_commentable_type_commentable_id_index` (`commentable_type` ASC, `commentable_id` ASC) VISIBLE,
  INDEX `comments_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `comments_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `orm`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 274
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `orm`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`groups` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `orm`.`group_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`group_user` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_id` BIGINT(20) UNSIGNED NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `group_user_group_id_foreign` (`group_id` ASC) VISIBLE,
  INDEX `group_user_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `group_user_group_id_foreign`
    FOREIGN KEY (`group_id`)
    REFERENCES `orm`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `group_user_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `orm`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `orm`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`images` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NOT NULL,
  `imageable_type` VARCHAR(255) NOT NULL,
  `imageable_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `images_imageable_type_imageable_id_index` (`imageable_type` ASC, `imageable_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 86
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `orm`.`levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`levels` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `orm`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`profiles` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `dni` VARCHAR(45) NULL,
  `valoration` INT NULL,
  `description` VARCHAR(45) NULL,
  `facebook` VARCHAR(255) NULL DEFAULT NULL,
  `instagram` VARCHAR(255) NULL DEFAULT NULL,
  `twitter` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `profiles_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `profiles_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `orm`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `orm`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`locations` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `profile_id` BIGINT(20) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `state` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `locations_profile_id_foreign` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `locations_profile_id_foreign`
    FOREIGN KEY (`profile_id`)
    REFERENCES `orm`.`profiles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `orm`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `orm`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `orm`.`taks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`taks` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` BIGINT(20) UNSIGNED NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `posts_category_id_foreign` (`category_id` ASC) VISIBLE,
  INDEX `posts_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `posts_category_id_foreign`
    FOREIGN KEY (`category_id`)
    REFERENCES `orm`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `posts_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `orm`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `orm`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`tags` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `orm`.`taggables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`taggables` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tag_id` BIGINT(20) UNSIGNED NOT NULL,
  `taggable_type` VARCHAR(255) NOT NULL,
  `taggable_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `taggables_taggable_type_taggable_id_index` (`taggable_type` ASC, `taggable_id` ASC) VISIBLE,
  INDEX `taggables_tag_id_foreign` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `taggables_tag_id_foreign`
    FOREIGN KEY (`tag_id`)
    REFERENCES `orm`.`tags` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 364
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `orm`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`videos` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` BIGINT(20) UNSIGNED NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `videos_category_id_foreign` (`category_id` ASC) VISIBLE,
  INDEX `videos_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `videos_category_id_foreign`
    FOREIGN KEY (`category_id`)
    REFERENCES `orm`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `videos_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `orm`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `orm`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`roles` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orm`.`role_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`role_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT(20) UNSIGNED NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `roles_user_user_id_foreign_idx` (`user_id` ASC) VISIBLE,
  INDEX `roles_user_roler_id_foreign_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `roles_user_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `orm`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `roles_user_roler_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `orm`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orm`.`studies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`studies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profile_id` BIGINT(20) UNSIGNED NOT NULL,
  `title` VARCHAR(45) NULL,
  `company` VARCHAR(45) NULL,
  `date_start` DATE NULL,
  `date_end` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `studies_profile_if_forg_idx` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `studies_profile_if_forg`
    FOREIGN KEY (`profile_id`)
    REFERENCES `orm`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orm`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profile_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `skill_profile_id_forign_idx` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `skill_profile_id_forign`
    FOREIGN KEY (`profile_id`)
    REFERENCES `orm`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orm`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`files` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NOT NULL,
  `filable_type` VARCHAR(255) NOT NULL,
  `filable_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `images_imageable_type_imageable_id_index` (`filable_type` ASC, `filable_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 86
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `orm`.`deposits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`deposits` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `number_acount` VARCHAR(45) NULL,
  `type_acount` VARCHAR(45) NULL,
  `name_bank` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `deposits_user_id_forgin_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `deposits_user_id_forgin`
    FOREIGN KEY (`user_id`)
    REFERENCES `orm`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orm`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm`.`payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `number_acount` VARCHAR(45) NULL,
  `type_acount` VARCHAR(45) NULL,
  `name_bank` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `payments_user_id_forign_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `payments_user_id_forign`
    FOREIGN KEY (`user_id`)
    REFERENCES `orm`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
